services:
  postgres:
    image: "postgres:16.6-alpine3.21"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controleProcessos
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./controle-processos-server/src/Api
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=controleProcessos;Username=postgres;Password=postgres
    ports:
      - "5000:80"

  # frontend:
  #   build: ./controle-processos-frontend
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - api

volumes:
  pgdata:
